name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to test'
        required: true
        default: '1.0.0'


permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run lint
      - run: npm test

  build:
    name: Build bundle
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
      - name: Setup Git
        run: |
          git config --global user.email "${{ github.actor }}"
          git config --global user.name "${{ github.repository_owner }}"
          git checkout -b release/${{ github.event.inputs.version }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build
      - name: Clean files
        run: |
          rm .gitignore
          rm -Rf node_modules/
          rm -Rf .github
          rm index.js
      - name: Git Create Branch release/${{ github.event.inputs.version }}
        run: |
          git add .
          git commit -m "Auto commit from Github Actions #${{ github.run_id }}"
          git push origin release/${{ github.event.inputs.version }} -f
        # git tag v${{ github.event.inputs.version }} release/${{ github.event.inputs.version }}

  deploy:
    name: Deploy Bundle
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - name: Set Time
        id: set-time
        run: echo "TIME=$(date --rfc-3339=date)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v/${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          commitish: release/${{ github.event.inputs.version }}
          body: |
            Created on ${{ steps.set-time.outputs.TIME }} using automated Workflow by ${{ github.actor }}
          draft: false
          prerelease: false
